#!/bin/bash
#
#   Author:         Brian Vanderwende
#   Last Revised:   13:13, 09 Oct 2026
#

set -e
export SPACKLOT_DIR="$( cd "$(dirname "$0")" ; pwd )"
export SPACKLOT_DEPLOYMENT_TIME=$(date +%y%m%dT%H%M)
export SPACKLOT_DEPLOYMENT_TYPE=testing
export SPACK_DISABLE_LOCAL_CONFIG=true

# Source functions from init script, but skip environment activation
SPACKLOT_SETUP_DEPLOY=1 . $SPACKLOT_DIR/src/build/bin/tools/init.sh

function usage {
cat << EOF
Usage: $0 [OPTIONS] CLUSTER

This script is used to deploy a new Spack software stack based on a specified
cluster definition. A "build" environment will be created, and by default all
packages defined in the cluster's manifest will be built. Publishing will not
be done by this script.

Options
    -h, --help                  show this help message
    -b, --branch REF            override the branch of the Spack repo to use
    -c, --collection NAME       use definitions from clusters/NAME
    -k, --key OPTION            determines behavior for GPG keys. options include:
                                    auto    - generate if not found at normal path
                                    PATH    - specify the path to a private GPG key
                                    new     - force generation of a new key
                                    none    - don't generate or import keys
    -p, --production            create a production deployment (must be prod user)
    -r, --repo REF              override the branch of the builtin packages repo
    -s, --skip STEP1[,STEP2]        skip specified step of deployment process
                                    all         - skip all of the below
                                    bootstrap   - don't do bootstrap concretization
                                    constraints - don't add constraints
                                    keys        - don't set up GPG keys
                                    mirrors     - don't set up local+global mirrors
                                    packages    - don't install anything into build
                                    repos       - don't set up package repos
    --share-builtin PATH        use builtin packages repo at the following path
                                (package repo must be owned by current user)
    --set-version VERSION       override version set in cluster definition

EOF
exit ${1:-0}
}

function export_gpg_key {
    echo
    tsecho "Exporting new GPG key to $SPACKLOT_KEY_DIRECTORY ..."
    spack gpg export $SPACKLOT_KEY_DIRECTORY/${key_user}-key.pub
    spack gpg export --secret $SPACKLOT_KEY_DIRECTORY/${key_user}-key.priv
    chmod 640 $SPACKLOT_KEY_DIRECTORY/${key_user}-key.*
    echo
}

#
## ---- INITIALIZATION ----
#

# Helper variables that can be refenced in cluster's main.cfg
export SPACKLOT_DEPLOYMENT_DATE=$(date +%y.%m)
export SPACKLOT_SYSTEM_GCC=gcc@$(/usr/bin/gcc -dumpfullversion)

# Handle arguments
user_args=( "$@" )
gpg_opt=auto
key_user=$(whoami)

while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
        -h|--help)
            usage
            ;;
        -b|--branch)
            custom_branch_spack=$2
            shift
            ;;
        -c|--collection)
            custom_collection="$2"
            shift
            ;;
        -k|--key)
            gpg_opt=$2
            shift
            ;;
        -p|--production)
            SPACKLOT_DEPLOYMENT_TYPE=production
            ;;
        -r|--repo)
            custom_branch_builtin=$2
            shift
            ;;
        -s|--skip)
            if [[ $1 == *=* ]]; then
                skip_steps=${1#*=}
            else
                skip_steps=$2
                shift
            fi

            skip_steps=" $(tr ',' ' ' <<< $skip_steps) "
            ;;
        --set-version)
            custom_version=$2

            if [[ -n $custom_version ]]; then
                tmp_file_path=$(mktemp ${TMPDIR:-/tmp}/ns-cluster.XXXXXXXX)
                shift
            else
                tsecho "Error: --set-version requires an argument"
                usage 1
            fi
            ;;
        --share-builtin)
            packages_path=$2

            if [[ ! -f $packages_path/repos/spack_repo/builtin/repo.yaml ]]; then
                tsecho "Error: path given for existing builtin is not a repo directory"
                exit 1
            else
                pkg_repo_owner=$(stat -c '%U' $packages_path)

                if [[ $(whoami) != $pkg_repo_owner ]]; then
                    tsecho "Error: shared package repo must be owned by current user"
                    exit 1
                fi
            fi
            ;;
        -*)
            tsecho "Error: unrecognized option $key"
            usage 1
            ;;
        *)
            export SPACKLOT_DEPLOYMENT_NAME=$1
            ;;
    esac

    shift
done

# Source specified config
if [[ -z $custom_collection ]]; then
    if [[ ! -e $SPACKLOT_DIR/clusters/deploy.cfg ]]; then
        ln -s $SPACKLOT_DIR/clusters/default/deploy.cfg $SPACKLOT_DIR/clusters/deploy.cfg
    fi

    . $SPACKLOT_DIR/clusters/deploy.cfg
else
    . $SPACKLOT_DIR/clusters/$custom_collection/deploy.cfg
fi

export SPACKLOT_PRODUCTION_USER
cluster_dir=$SPACKLOT_DIR/clusters/$SPACKLOT_COLLECTION/$SPACKLOT_DEPLOYMENT_NAME

# Check for mandatory cluster components
for component in main.cfg spack.yaml; do
    if [[ ! -e $cluster_dir/$component ]]; then
        tsecho "Error: Cluster $SPACKLOT_DEPLOYMENT_NAME missing required component $component"
        exit 1
    fi
done

if [[ $SPACKLOT_DEPLOYMENT_TYPE == production ]]; then
    if [[ $key_user != $SPACKLOT_PRODUCTION_USER ]]; then
        tsecho "Error: cannot create production deployment as $my_user"
        exit 1
    fi
fi

if [[ -z $SPACKLOT_DEPLOYMENT_NAME ]]; then
    tsecho "Error: deployment configuration must be specified"
    usage 1
fi

if [[ -n $packages_path ]] && [[ -n $custom_branch_builtin ]]; then
    tsecho "Error: cannot specify both --repo and --share-packages"
    usage 1
fi

# Source cluster settings
if [[ -n $tmp_file_path ]]; then
    settings_file=$tmp_file_path
    sed "s/\(SPACKLOT_CLUSTER_VERSION=\).*/\1${custom_version}/" \
        $cluster_dir/main.cfg > $settings_file
else
    settings_file=$cluster_dir/main.cfg
fi

. $settings_file

# Check if Github repo exists
if [[ -n $SPACKLOT_GITHUB ]] && [[ $skip_github != yes ]]; then
    tsecho "Checking status of $SPACKLOT_GITHUB"

    if ! git ls-remote -h "$SPACKLOT_GITHUB" > /dev/null; then
        exit 1
    fi
fi

# Check key status
if [[ ! $gpg_opt =~ (auto|new|none) ]]; then
    if [[ ! -f $gpg_opt ]]; then
        tsecho "Error: No GPG key found at ${gpg_opt}.\n       Check input and try again."
        exit 1
    else
        gpg_key=$gpg_opt
    fi
elif [[ $gpg_opt == auto ]]; then
    if [[ -f $SPACKLOT_KEY_DIRECTORY/${key_user}-key.priv ]]; then
        gpg_key=$SPACKLOT_KEY_DIRECTORY/${key_user}-key.priv
    else
        gpg_opt=new
    fi
fi

# Ensure no ~/.spack contamination
if [[ -d ~/.spack ]]; then
    tsecho "Moving ~/.spack to ~/.spack-backups to avoid contamination"

    backup_root=~/.spack-backups
    mkdir -p $backup_root
    mv ~/.spack $backup_root/$(date +%y%m%d-%H%M%S)
fi

#
## ---- INSTALL/CLONE SPACK FOR CLUSTER ----
#

spack_clone_path=$SPACKLOT_ROOT_DEPLOYMENT/spack

if [[ $SPACKLOT_ROOT != $spack_clone_path ]]; then
    if [[ -d $SPACKLOT_ROOT_DEPLOYMENT ]]; then
        tsecho "Error:  Existing deployment found at ${SPACKLOT_ROOT_DEPLOYMENT}. Will not\n        overwrite. Resolve and rerun this script."
        exit 1
    fi

    # Install latest source from GitHub and checkout specified version
    tsecho "Installing ${GCOL}Spack${DCOL} into ${PCOL}$spack_clone_path${DCOL}"
    echo
    git clone -c feature.manyFiles=true ${SPACKLOT_URL_SPACK:-${SPACKLOT_DEFAULT_URL_SPACK:-https://github.com/spack/spack.git}} $spack_clone_path
    echo
    cd $spack_clone_path

    if [[ -n $custom_branch_spack ]]; then
        SPACKLOT_BRANCH_SPACK=$custom_branch_spack
    fi

    if [[ -n $SPACKLOT_BRANCH_SPACK ]]; then
        tsecho " >> Switching to custom Spack branch ${PCOL}${SPACKLOT_BRANCH_SPACK}$DCOL"
        echo
        git checkout $SPACKLOT_BRANCH_SPACK
        echo
    elif git branch -r | grep -q /$SPACKLOT_CLUSTER_VERSION; then
        tsecho " >> Switching to existing cluster version branch ${PCOL}${SPACKLOT_CLUSTER_VERSION}$DCOL"
        echo
        git checkout $SPACKLOT_CLUSTER_VERSION
        echo
    fi

    # Add original Spack repo as an upstream for checking out recipe updates
    if [[ $SPACKLOT_DEFAULT_SPACK_BRANCH != https://github.com/spack/spack.git ]]; then
        git remote add upstream https://github.com/spack/spack.git
    fi

    # Copy our scripts into the clone
    cp -r $SPACKLOT_DIR/src/spack/* $spack_clone_path

    # Set prompt label in init script
    sed -i "s/\[clean\]/\[${SPACKLOT_CLUSTER}-${SPACKLOT_CLUSTER_VERSION}\]/" $spack_clone_path/share/spacklot/init.sh

    # If exists, use Spack utils repo for Python
    if [[ -d $SPACKLOT_PYTHON_ROOT ]]; then
        sed -i "s|^\(SPACKLOT_PYTHON_ROOT=\).*|\1$SPACKLOT_PYTHON_ROOT|" $spack_clone_path/share/spacklot/init.sh
    fi

    if [[ -n $SPACKLOT_SPACK_PYDIR ]]; then
        sed -i "/^env_args=/a SPACKLOT_SPACK_PYDIR=$SPACKLOT_SPACK_PYDIR" $spack_clone_path/bin/clean_bash
    fi

    # Add custom cluster source files if found
    if [[ -d $cluster_dir/src/spack ]]; then
        cp -r $cluster_dir/src/spack/* $spack_clone_path/
    fi

    # Copy any found licenses to Spack install
    if [[ -d $cluster_dir/licenses ]]; then
        cp -rL $cluster_dir/licenses $spack_clone_path/etc/spack/
    fi

    # Modify permissions
    chmod -R a=rX,u+w $spack_clone_path

    # Activate spack installation
    . $spack_clone_path/share/spack/setup-env.sh

    # Pull builtin package repo
    if [[ ! $skip_steps =~ " "(repos|all)" " ]]; then
        for repo_root_var in ${!SPACKLOT_ROOT_PACKAGES_*}; do
            repo_name=${repo_root_var#SPACKLOT_ROOT_PACKAGES_}
            repo_branch_var=SPACKLOT_BRANCH_PACKAGES_$repo_name
            repo_url_var=SPACKLOT_URL_PACKAGES_$repo_name
            repo_root=${!repo_root_var}
            repo_branch=${!repo_branch_var}
            repo_url=${!repo_url_var}

            if [[ $repo_name == BUILTIN ]]; then
                repo_root=${repo_root:-$SPACKLOT_ROOT_PACKAGES}
                repo_url=${repo_url:-${SPACKLOT_DEFAULT_URL_PACKAGES_BUILTIN:-https://github.com/spack/spack-packages.git}}
                repo_branch=${custom_branch_builtin:-${repo_branch:-$SPACKLOT_DEFAULT_BRANCH_PACKAGES_BUILTIN}}
            fi

            if [[ $repo_name == BUILTIN ]] && [[ -n $packages_path ]]; then
                tsecho "Linking existing ${GCOL}builtin$DCOL repo into deployment"
                ln -s $packages_path $repo_root

                if [[ -n $SPACKLOT_BRANCH_PACKAGES_BUILTIN ]]; then
                    tsecho " >> Ignoring branch specified in config file since we are using existing repo"
                fi
            else
                tsecho "Pulling ${GCOL}${repo_name,,}$DCOL package repo into Spack clone"

                if [[ -z $repo_url ]]; then
                    tsecho "Error: No URL given for package repo ${repo_name,,}. Set $repo_url_var in main.cfg."
                    exit 1
                fi

                echo
                git clone $repo_url $repo_root
                cd $repo_root
                git remote set-url origin $repo_url
                echo

                if [[ $repo_name == BUILTIN ]] && [[ $repo_url != https://github.com/spack/spack-packages.git ]]; then
                    git remote add upstream https://github.com/spack/spack-packages.git
                fi

                if [[ -n $repo_branch ]]; then
                    tsecho " >> Switching to ${GCOL}${repo_name}$DCOL repo branch ${PCOL}${repo_branch}$DCOL"
                    echo
                    git fetch
                    git checkout origin/$repo_branch
                    echo
                fi
            fi

            cd - > /dev/null
            spack repo add $repo_root/repos/spack_repo/*
        done
    fi

    # Create trusted GPG key in spack install
    if [[ ! $skip_steps =~ " "(keys|all)" "  ]]; then
        if [[ $gpg_opt == new ]]; then
            if [[ $key_user == $SPACKLOT_PRODUCTION_USER ]]; then
                key_person="$SPACKLOT_PRODUCTION_USER_NAME"
                key_email=$SPACKLOT_PRODUCTION_USER_EMAIL
            else
                key_person="$(getent passwd $key_user | awk -F[,:] '{ print $5 }')"
                key_email=$SPACKLOT_USER_EMAIL
            fi

            tsecho "Creating trusted GPG key for build cache creation"
            spack gpg create "${key_person:-$key_user}" "<${key_email:-$(printf "%s@%s" $key_user $(hostname -f))}>"

            if [[ -f $SPACKLOT_KEY_DIRECTORY/${key_user}-key.priv ]]; then
                read -p "GPG key already exists. Overwrite (y/N)? " clobber_key
                clobber_key=${clobber_key:-no}

                if [[ yes == ${clobber_key,,}* ]]; then
                    echo "Backing up old key ..."
                    mkdir $SPACKLOT_KEY_DIRECTORY/backup.$SPACKLOT_DEPLOYMENT_TIME
                    mv $SPACKLOT_KEY_DIRECTORY/${key_user}-key.* $SPACKLOT_KEY_DIRECTORY/backup.$SPACKLOT_DEPLOYMENT_TIME
                    export_gpg_key
                fi
            else
                mkdir -p $SPACKLOT_KEY_DIRECTORY
                export_gpg_key
            fi
        elif [[ -n $gpg_key ]]; then
            tsecho "Trusting existing GPG key"
            spack gpg trust -y $gpg_key
            echo
        fi
    fi

    tsecho "Activating new spack installation"

    # Make sure environment is clean
    cd $SPACKLOT_DIR
    $spack_clone_path/bin/clean_bash $0 "${user_args[@]}"
    exit $?
else
    # Activate spack installation
    . $SPACKLOT_STARTUP
fi

#
## ---- CREATE AND CUSTOMIZE ENV ----
#

if [[ -d $SPACKLOT_ENV_BUILD ]]; then
>&2 cat << EOF
Error:  Existing environment found at ${SPACKLOT_ENV_BUILD}. Will not
        overwrite. Resolve and rerun this script.

EOF
exit 1
fi

tsecho "Creating env at ${GCOL}${SPACKLOT_ENV_BUILD}$DCOL"

# All spack needs for an env is a directory with spack.yaml
mkdir -p $SPACKLOT_ENV_BUILD/logs
cp $cluster_dir/spack.yaml $SPACKLOT_ENV_BUILD
cp -r src/build/* $SPACKLOT_ENV_BUILD
cp -r templates $SPACKLOT_ENV_BUILD

cat > $SPACKLOT_ENV_BUILD/main.cfg << EOF
SPACKLOT_DEPLOYMENT_TYPE=$SPACKLOT_DEPLOYMENT_TYPE
SPACKLOT_DEPLOYMENT_COMMIT=$(git rev-parse HEAD)
SPACKLOT_PRODUCTION_USER=$SPACKLOT_PRODUCTION_USER
SPACKLOT_COLLECTION=$SPACKLOT_COLLECTION

EOF

envsubst '$USER,$SPACKLOT_DEPLOYMENT_NAME,$SPACKLOT_DEPLOYMENT_DATE,$SPACKLOT_SYSTEM_GCC' < $settings_file >> $SPACKLOT_ENV_BUILD/main.cfg

if [[ -n $tmp_file_path ]]; then
    rm -f $tmp_file_path
fi

sed -i "s|^\(SPACKLOT_MAIN=\)$|\1$SPACKLOT_ENV_BUILD/main.cfg|" $spack_clone_path/bin/clean_bash

# Override the normal version if set at the command-line
if [[ -n $custom_version ]]; then
    sed -i "s/\(SPACKLOT_CLUSTER_VERSION=\).*/\1${custom_version}/" $SPACKLOT_ENV_BUILD/main.cfg
fi

# Copy components that may be optional
for component in packages.cfg templates postprocess includes; do
    if [[ -e $cluster_dir/$component ]]; then
        cp -r -L $cluster_dir/$component $SPACKLOT_ENV_BUILD
    else
        tsecho " -> Skipping optional component $PCOL$component$DCOL"
    fi
done

# Make cluster-specific substitutions in YAML FILES
for yaml_file in $SPACKLOT_ENV_BUILD/spack.yaml $(ls $SPACKLOT_ENV_BUILD/includes/* 2> /dev/null); do
    sed -i "s|%HOST%|$SPACKLOT_CLUSTER|" $yaml_file
    sed -i "s|%VERSION%|$SPACKLOT_CLUSTER_VERSION|" $yaml_file
    sed -i "s|%DEPLOYMENT%|${SPACKLOT_CLUSTER}/$SPACKLOT_CLUSTER_VERSION|" $yaml_file
    sed -i "s|%INSTALLROOT%|${SPACKLOT_ENV_BUILD}/opt|" $yaml_file
    sed -i "s|%MODULESROOT%|${SPACKLOT_ENV_BUILD}/modules/$SPACKLOT_CLUSTER_VERSION|" $yaml_file
    sed -i "s|%BASEROOT%|$SPACKLOT_ENV_BUILD|" $yaml_file
    sed -i "s|%TMPROOT%|$SPACKLOT_TMPROOT|g" $yaml_file
    sed -i "s|%SYSTEMGCC%|${SPACKLOT_SYSTEM_GCC#*@}|g" $yaml_file
done

# Activate the environment
spack env activate $SPACKLOT_ENV_BUILD
spack env status

# Make sure packages are concretized separately (to allow multiple variants)
spack config add 'concretizer:unify:false'

# Set Spack-version specific bootstrap path to avoid conflicts
tsecho "Set bookstrap location to ${GCOL}${SPACKLOT_ROOT_BOOTSTRAP}$DCOL"
spack bootstrap root $SPACKLOT_ROOT_BOOTSTRAP > /dev/null

# Add package constraints from initial config file
if [[ -f $cluster_dir/constraints.cfg ]]; then
    cp $cluster_dir/constraints.cfg $SPACKLOT_ENV_BUILD

    if [[ ! $skip_steps =~ " "(constraints|all)" "  ]]; then
        tsecho "Setting package constraints"
        $SPACKLOT_ENV_BUILD/bin/add_constraints
    fi
else
    tsecho "Skipping constraints step as cluster has no constraints.cfg"
fi

# Detect available external compilers (e.g., Cray compilers)
if [[ ${SPACKLOT_DETECT_COMPILERS:-false} == true ]]; then
    spack compiler find
fi

# Create mirrors and prepare env to generate build_cache binaries
if [[ $SPACKLOT_PAD_LENGTH != 0 ]]; then
    spack config add "config:install_tree:padded_length:${SPACKLOT_PAD_LENGTH:-128}"
fi

signing_keys=$(spack gpg list --signing | awk 'f{print;f=0} /^sec /{f=1}')

if [[ ! $skip_steps =~ " "(mirrors|all)" "  ]]; then
    for mtype in LOCAL GLOBAL; do
        mirror_variable=SPACKLOT_MIRROR_${mtype}
        mirror=${!mirror_variable}
        mirror_type=posix
        mirror_flags=

        if [[ -n $mirror ]]; then
            if [[ ! -d $mirror ]]; then
                if [[ $(sed 's/production/GLOBAL/;s/testing/LOCAL/' <<< $SPACKLOT_DEPLOYMENT_TYPE) == $mtype ]]; then
                    spack mirror create -d $mirror -a --private
                    mirror_flags="--type source"
                fi
            fi

            if [[ -d $mirror ]]; then
                tsecho "Adding disk mirror ${GCOL}${mirror}$DCOL"
                spack mirror add $mirror_flags hpc_mirror_${mtype,,} $mirror

                # Make sure signing keys are pushed (and index regenerated!)
                repo_owner=$(stat -c '%U' $mirror)

                if [[ $my_user == $repo_owner ]]; then
                    for key in $signing_keys; do
                        spack gpg publish --rebuild-index -m hpc_mirror_${mtype,,} $key
                    done
                fi
            fi
        fi
    done

    # Install any known keys from binary caches
    if spack mirror ls | awk -F[\]\[] '{ print $2 }' | grep -q b; then
        tsecho "Adding trusted keys from buildcaches"
        spack buildcache keys --install --trust
    fi
fi

# Add module templates
spack config add "config:template_dirs:$SPACK_ENV/templates/modules"

# Add any requested upstreams
for upstream_name in ${!SPACKLOT_UPSTREAMS[@]}; do
    spack config add "upstreams:${upstream_name}:install_tree:${SPACKLOT_UPSTREAMS[$upstream_name]}"
done

# If this is not done, we can get a bad first concretization result
if [[ ! $skip_steps =~ " "(bootstrap|all)" " ]]; then
    tsecho "Perform test concretization to trigger bootstrapping"
    spack spec zlib > /dev/null
else
    tsecho "Skipping bootstrapping (recommended before first install_packages run!)"
fi

#
## ---- BUILD PACKAGES IN ENVIRONMENTS ----
#

if [[ ! $skip_steps =~ " "(packages|all)" "  ]]; then
    if [[ -f packages.cfg ]]; then
        tsecho "Building packages in build environment"
        echo

        # Build packages from source in build environment
        cd $SPACKLOT_ENV_BUILD
        bin/install_packages

        # Run script to populate the binary build_cache
        if [[ $SPACKLOT_PAD_LENGTH != 0 ]]; then
            tsecho "Populating build cache with package binaries"
            echo
            bin/populate_build_cache
        else
            tsecho "Skipping build cache due to pad length = 0"
        fi

        # Create modules in build environment
        if [[ -n $SPACKLOT_ROOT_MODULES ]]; then
            tsecho "Generating modules in build environment"
            spack module lmod refresh -y
        fi

        # Some clusters (e.g., Cray) need to run extra commands to prep environment
        if [[ -d $SPACKLOT_ENV_BUILD/postprocess ]]; then
            tsecho "Running postprocessing on the build environment"
            $SPACKLOT_ENV_BUILD/bin/postprocess
        fi
    else
        tsecho "Skipping packages step as cluster has no packages.cfg"
    fi
fi

spack env deactivate

# Status message
cat << EOF

====================================
    SPACKLOT DEPLOYMENT COMPLETE
====================================

Machine:        $SPACKLOT_DEPLOYMENT_NAME
Date:           $SPACKLOT_DEPLOYMENT_TIME
Type:           $SPACKLOT_DEPLOYMENT_TYPE

Spack root:     $SPACK_ROOT
Build root:     $SPACKLOT_ENV_BUILD
Public root:    $SPACKLOT_ENV_PUBLIC
Package root:   ${packages_path:-$SPACKLOT_ROOT_PACKAGES_BUILTIN}

Github repo:    ${SPACKLOT_GITHUB:-none}
Spack branch:   ${SPACKLOT_BRANCH_SPACK:-${SPACKLOT_DEFAULT_BRANCH_SPACK:-develop}}
Builtin branch: ${SPACKLOT_BRANCH_PACKAGES_BUILTIN:-${SPACKLOT_DEFAULT_BRANCH_PACKAGES_BUILTIN:-develop}}

EOF

if [[ ${skip_pkgs:-no} != yes ]]; then
cat << EOF
Install logs:   $SPACKLOT_ENV_BUILD/logs/installs.$SPACKLOT_DEPLOYMENT_TIME
Caching logs:   $SPACKLOT_ENV_BUILD/logs/cache.$SPACKLOT_DEPLOYMENT_TIME

EOF
fi

cat << EOF
*** First check that builds in build environment are valid! ***

To install into $SPACKLOT_DEPLOYMENT_TYPE public environment, run the following:

$SPACKLOT_ENV_BUILD/bin/publish "Initial deployment of environment on $SPACKLOT_DEPLOYMENT_NAME"

EOF
